export interface LocationData {
  city: string;
  state: string;
  stateCode: string;
  slug: string;
  zipCodes: string[];
  climate: string;
  commonRisks: string[];
  localContent: {
    intro: string;
    risks: string;
  };
}

export const locations: LocationData[] = [
    // Arizona
  {
    city: "Phoenix",
    state: "Arizona",
    stateCode: "AZ",
    slug: "phoenix-az",
    zipCodes: ["85001", "85003", "85004", "85006", "85007", "85008", "85009", "85012", "85013", "85014"],
    climate: "a hot desert climate with very long, hot summers and short, mild winters.",
    commonRisks: ["intense sun exposure", "monsoon storms", "high winds", "uv degradation"],
    localContent: {
        intro: "In a city like Phoenix where the sun beats down relentlessly, a roof is more than just a cover—it's your home's first line of defense against extreme heat and UV radiation. The intense desert climate demands specific roofing materials and expertise to ensure longevity and energy efficiency. Homeowners here often choose materials with high solar reflectivity to keep their homes cooler and reduce energy bills.",
        risks: "Beyond the sun, Phoenix roofs must withstand sudden, violent monsoon storms that bring high winds and torrential rain. This combination can easily exploit any small weakness, turning a minor issue into a major leak. Dust storms, or 'haboobs,' can also scour roofing surfaces over time. Our network roofers are experts in sealing and securing roofs to stand up to Arizona's unique weather patterns, from tile roof maintenance to complete asphalt shingle replacements."
    }
  },
  // Texas
  {
    city: "Houston",
    state: "Texas",
    stateCode: "TX",
    slug: "houston-tx",
    zipCodes: ["77002", "77003", "77004", "77005", "77006", "77007", "77008", "77009", "77010", "77011"],
    climate: "a humid subtropical climate, with hot, humid summers and mild winters.",
    commonRisks: ["hurricanes", "hailstorms", "heavy rainfall", "high winds"],
    localContent: {
        intro: "Houston's proximity to the Gulf of Mexico defines its roofing needs. The climate is characterized by extreme humidity, high heat, and the constant threat of tropical storms and hurricanes. A roof in Houston isn't just for shade; it's a critical component of your home's defense system against severe weather. Proper installation and material choice are paramount to prevent catastrophic failure during a storm.",
        risks: "Hurricanes and the accompanying wind-driven rain are the primary threats. Roofs must be rated for high wind speeds, and flashing must be impeccably installed to prevent water intrusion. Furthermore, the heat and humidity create a perfect environment for algae and mold growth on shingles, which can degrade the roof over time. The roofers in our network are well-versed in hurricane-ready roofing techniques and materials that resist organic growth."
    }
  },
  {
    city: "Dallas",
    state: "Texas",
    stateCode: "TX",
    slug: "dallas-tx",
    zipCodes: ["75201", "75202", "75203", "75204", "75205", "75206", "75207", "75208", "75209", "75210"],
    climate: "a humid subtropical climate with very hot summers, requiring roofs that can handle extreme heat and intense sun.",
    commonRisks: ["severe hailstorms", "tornadoes", "strong winds", "intense sun exposure"],
    localContent: {
        intro: "Dallas is located in the heart of 'Hail Alley,' making it one of the most at-risk cities in the nation for severe roof damage. The combination of intense summer heat, UV exposure, and the frequent threat of large, destructive hail means that a standard roof often isn't enough. Investing in impact-resistant materials is not a luxury here; it's a wise financial decision.",
        risks: "Severe hailstorms are the number one enemy of Dallas roofs, capable of shattering shingles and denting metal. Beyond hail, the area is prone to tornadoes and straight-line winds that can peel shingles off a roof with ease. The intense Texas sun also bakes shingles, causing them to become brittle and fail prematurely. We connect you with Dallas-Fort Worth roofers who specialize in Class 4 impact-resistant shingles and other durable solutions designed for this challenging environment."
    },
  },
  // And all other locations... the rest have been omitted for brevity but would follow this pattern.
  { city: "Mesa", state: "Arizona", stateCode: "AZ", slug: "mesa-az", zipCodes: ["85201", "85202", "85203", "85204", "85205"], climate: "a hot desert climate, similar to Phoenix, where reflective and heat-resistant roofing is critical.", commonRisks: ["intense sun exposure", "haboobs (dust storms)", "sudden downpours"], localContent: { intro: "Mesa's desert climate presents unique challenges, where extreme heat and sun are the primary concerns for any roof.", risks: "Reflective roofing materials are key in Mesa to combat the heat island effect and lower energy costs. Monsoon season also brings sudden, intense rain and wind." } },
  { city: "Scottsdale", state: "Arizona", stateCode: "AZ", slug: "scottsdale-az", zipCodes: ["85250", "85251", "85253", "85254", "85255"], climate: "a hot arid climate where roofs must endure extreme summer heat and strong sunlight.", commonRisks: ["intense sun exposure", "monsoon storms", "tile roof maintenance"], localContent: { intro: "In upscale Scottsdale, roof aesthetics are as important as performance. Tile and high-end architectural shingles are popular choices.", risks: "These materials must be correctly installed to withstand monsoon storms and intense UV rays, which can cause fading and cracking over time." } },
  { city: "Los Angeles", state: "California", stateCode: "CA", slug: "los-angeles-ca", zipCodes: ["90001", "90002", "90003", "90004", "90005"], climate: "a Mediterranean climate with hot, dry summers and mild, wet winters. Title 24 compliance for cool roofs is a key factor.", commonRisks: ["intense sun exposure", "wildfire embers", "earthquakes (requires secure fastening)"], localContent: { intro: "Los Angeles roofing is governed by strict energy codes like Title 24, requiring 'cool roof' materials to reflect sunlight.", risks: "Besides heat, roofs in hillside communities must be built with fire-resistant materials to protect against embers from wildfires." } },
  { city: "San Diego", state: "California", stateCode: "CA", slug: "san-diego-ca", zipCodes: ["92101", "92102", "92103", "92104", "92105"], climate: "a mild Mediterranean climate year-round, but coastal salt air can accelerate corrosion on certain roofing materials.", commonRisks: ["salt air corrosion", "intense sun exposure", "wildfire risk in inland areas"], localContent: { intro: "San Diego's idyllic climate is tempered by coastal salt spray, which can be highly corrosive to metal roofing components.", risks: "Choosing corrosion-resistant materials is vital for longevity. Inland areas face a significant wildfire threat, demanding Class A fire-rated roofing systems." } },
  { city: "San Jose", state: "California", stateCode: "CA", slug: "san-jose-ca", zipCodes: ["95101", "95110", "95111", "95112", "95113"], climate: "a mild Mediterranean climate with warm, dry summers and cool, wet winters.", commonRisks: ["intense sun exposure", "heat absorption", "winter rain leaks"], localContent: { intro: "In the heart of Silicon Valley, San Jose homes benefit from energy-efficient roofing that can handle hot, dry summers.", risks: "While winters are mild, they are wet, and older roofs are prone to leaks if not properly maintained." } },
  { city: "Sacramento", state: "California", stateCode: "CA", slug: "sacramento-ca", zipCodes: ["95811", "95814", "95815", "95816", "95817"], climate: "a hot-summer Mediterranean climate, with very hot, dry summers requiring energy-efficient roofing.", commonRisks: ["extreme summer heat", "heavy rain in winter", "tree debris"], localContent: { intro: "Sacramento's scorching summers make 'cool roofs' a necessity for comfort and energy savings.", risks: "The city's many trees, while beautiful, can drop leaves and debris that clog gutters and cause water damage if not regularly cleared." } },
  { city: "Fresno", state: "California", stateCode: "CA", slug: "fresno-ca", zipCodes: ["93650", "93701", "93702", "93703", "93704"], climate: "a semi-arid climate with very hot, dry summers and cool, damp winters, with dense Tule fog.", commonRisks: ["extreme heat", "UV degradation", "poor air quality affecting materials"], localContent: { intro: "Fresno's climate demands roofs that can withstand extreme heat and UV radiation during the summer.", risks: "The dense winter Tule fog can trap moisture on roofing surfaces, accelerating wear if not properly ventilated." } },
  { city: "Denver", state: "Colorado", stateCode: "CO", slug: "denver-co", zipCodes: ["80202", "80203", "80204", "80205", "80206"], climate: "a semi-arid climate with four distinct seasons. High altitude means intense UV exposure and a high risk of severe hailstorms.", commonRisks: ["severe hailstorms", "high winds", "heavy snowfall", "intense sun exposure"], localContent: { intro: "Denver roofing is all about durability. The Mile High City's altitude means more intense UV rays and its location makes it a magnet for severe hailstorms.", risks: "Impact-resistant shingles (Class 4) are the standard recommendation here to avoid costly damage from the frequent and often large hail." } },
  { city: "Aurora", state: "Colorado", stateCode: "CO", slug: "aurora-co", zipCodes: ["80010", "80011", "80012", "80013", "80014"], climate: "similar to Denver, it experiences frequent and severe hail, making impact-resistant shingles (Class 4) a popular choice.", commonRisks: ["large hail", "strong winds", "freeze-thaw cycles", "heavy snow loads"], localContent: { intro: "Like its neighbor Denver, Aurora is prime territory for hail damage. Roofs must be built to withstand severe impacts.", risks: "Heavy snow loads in winter and rapid freeze-thaw cycles in spring add further stress to roofing materials." } },
  { city: "Colorado Springs", state: "Colorado", stateCode: "CO", slug: "colorado-springs-co", zipCodes: ["80903", "80904", "80905", "80906", "80907"], climate: "located at the foot of the Rockies, it is highly prone to severe hailstorms, high winds, and rapid temperature changes.", commonRisks: ["severe hailstorms", "high winds", "wildfire risk", "heavy snow"], localContent: { intro: "Colorado Springs combines the hail risk of the plains with the wind and snow risk of the mountains.", risks: "Violent winds coming off the mountains can cause significant shingle blow-offs, and proximity to forested areas introduces a wildfire risk." } },
  { city: "Miami", state: "Florida", stateCode: "FL", slug: "miami-fl", zipCodes: ["33101", "33109", "33125", "33126", "33127"], climate: "a tropical monsoon climate, prone to hurricanes and tropical storms, demanding robust, high-wind-rated roofing solutions.", commonRisks: ["hurricanes", "high winds", "heavy rainfall", "intense sun exposure"], localContent: { intro: "In Miami, roofing codes are among the strictest in the country for good reason. Roofs must be designed to withstand hurricane-force winds.", risks: "Beyond wind, the intense UV exposure and humid, salty air require materials that resist corrosion and degradation." } },
  { city: "Fort Lauderdale", state: "Florida", stateCode: "FL", slug: "fort-lauderdale-fl", zipCodes: ["33301", "33304", "33305", "33306", "33308"], climate: "a tropical rainforest climate, with significant hurricane risk and high humidity.", commonRisks: ["hurricanes", "wind-driven rain", "salt air corrosion", "high humidity"], localContent: { intro: "Fort Lauderdale's roofing requirements mirror Miami's, with a heavy emphasis on high-wind resistance and moisture control.", risks: "The constant humidity makes proper attic ventilation essential to prevent mold and mildew growth in the roof structure." } },
  { city: "West Palm Beach", state: "Florida", stateCode: "FL", slug: "west-palm-beach-fl", zipCodes: ["33401", "33403", "33404", "33405", "33406"], climate: "a tropical climate with a high risk of hurricanes and severe thunderstorms.", commonRisks: ["hurricanes", "high winds", "torrential rain", "intense sun exposure"], localContent: { intro: "West Palm Beach homeowners must prioritize roofing systems designed for the high-wind conditions of a hurricane.", risks: "Tile and metal roofs are popular choices for their durability, but they must be installed to the latest code standards to be effective." } },
  { city: "Orlando", state: "Florida", stateCode: "FL", slug: "orlando-fl", zipCodes: ["32801", "32803", "32804", "32805", "32806"], climate: "a humid subtropical climate with a strong wet season, leading to frequent thunderstorms and hurricane risk.", commonRisks: ["hurricanes", "hailstorms", "high humidity causing algae growth", "heavy rainfall"], localContent: { intro: "While inland, Orlando is still frequently impacted by hurricanes and strong thunderstorms that spin off them.", risks: "The humid climate is a breeding ground for algae, which causes unsightly black streaks on shingles and can shorten a roof's lifespan." } },
  { city: "Tampa", state: "Florida", stateCode: "FL", slug: "tampa-fl", zipCodes: ["33602", "33603", "33604", "33605", "33606"], climate: "a humid subtropical climate on the Gulf Coast, making it vulnerable to hurricanes and tropical storms.", commonRisks: ["hurricanes", "high winds", "storm surge", "high humidity"], localContent: { intro: "Tampa's position on the Gulf Coast makes it highly vulnerable to direct hits from hurricanes and tropical storms.", risks: "High winds and torrential, wind-driven rain are the primary concerns that a robust roofing system must be able to handle." } },
  { city: "Jacksonville", state: "Florida", stateCode: "FL", slug: "jacksonville-fl", zipCodes: ["32202", "32204", "32205", "32206", "32207"], climate: "a humid subtropical climate with milder winters than South Florida but still at risk from hurricanes and nor'easters.", commonRisks: ["hurricanes", "high winds", "heavy rainfall", "hail"], localContent: { intro: "Jacksonville's climate is a mix of Florida's hurricane risk and the seasonal changes of Georgia.", risks: "It is susceptible to both summer hurricanes and strong coastal storms known as nor'easters in the winter." } },
  { city: "Atlanta", state: "Georgia", stateCode: "GA", slug: "atlanta-ga", zipCodes: ["30303", "30305", "30306", "30307", "30308"], climate: "a humid subtropical climate known for hot, humid summers and occasional winter ice storms.", commonRisks: ["high winds from thunderstorms", "hail", "tree limbs falling", "ice storms"], localContent: { intro: "Atlanta's dense tree cover is both a blessing and a curse for roofs. While providing shade, it also means a higher risk of damage from fallen limbs.", risks: "Severe pop-up thunderstorms in the summer frequently bring high winds and hail. In winter, occasional ice storms can weigh down branches and cause significant damage." } },
  { city: "Marietta", state: "Georgia", stateCode: "GA", slug: "marietta-ga", zipCodes: ["30006", "30008", "30060", "30062", "30064"], climate: "similar to Atlanta, with a high risk of damage from severe thunderstorms and falling pine trees.", commonRisks: ["hail", "wind damage", "pine needle buildup in gutters", "high humidity"], localContent: { intro: "Marietta shares Atlanta's climate challenges, with a particular nuisance from the area's many pine trees.", risks: "Pine needles are notorious for clogging gutters, which can lead to water backing up under the shingles and causing rot." } },
  { city: "Chicago", state: "Illinois", stateCode: "IL", slug: "chicago-il", zipCodes: ["60601", "60602", "60603", "60604", "60605"], climate: "a humid continental climate with hot summers, cold, snowy winters, and strong winds off Lake Michigan.", commonRisks: ["heavy snow loads", "ice dams", "high winds", "freeze-thaw cycles"], localContent: { intro: "Chicago winters are tough on roofs. Heavy, wet snow can put immense strain on a roof's structure.", risks: "The biggest threat is 'ice dams'—ridges of ice that form at the edge of a roof, preventing melting snow from draining and forcing it under the shingles." } },
  { city: "Naperville", state: "Illinois", stateCode: "IL", slug: "naperville-il", zipCodes: ["60540", "60563", "60564", "60565"], climate: "experiences the full range of Midwestern weather, from hot summers to brutally cold winters with significant snowfall.", commonRisks: ["ice dams", "heavy snow", "hailstorms", "high winds"], localContent: { intro: "The Chicago suburb of Naperville faces the same harsh winter conditions, where proper attic insulation and ventilation are key.", risks: "These elements work together to prevent ice dams and protect the roof structure from moisture and rot." } },
  { city: "New Orleans", state: "Louisiana", stateCode: "LA", slug: "new-orleans-la", zipCodes: ["70112", "70113", "70114", "70115", "70116"], climate: "a humid subtropical climate with a very high risk of hurricanes, tropical storms, and heavy rainfall.", commonRisks: ["hurricanes", "torrential rain and flooding", "high humidity and mold growth", "storm surge"], localContent: { intro: "New Orleans roofs must be prepared for the worst-case scenario: a major hurricane. Building codes reflect this extreme risk.", risks: "Torrential rainfall, even outside of a hurricane, can overwhelm inadequate drainage systems, and the high humidity is a constant battle against mold and mildew." } },
  { city: "Baton Rouge", state: "Louisiana", stateCode: "LA", slug: "baton-rouge-la", zipCodes: ["70801", "70802", "70803", "70805", "70806"], climate: "inland from the coast but still very susceptible to hurricane remnants, high winds, and heavy rainfall.", commonRisks: ["hurricanes", "high winds", "hailstorms", "heavy rainfall"], localContent: { intro: "Though further inland than New Orleans, Baton Rouge is still highly susceptible to high winds and heavy rain from tropical systems.", risks: "The city also sees its fair share of severe thunderstorms that can produce damaging hail and winds." } },
  { city: "Minneapolis", state: "Minnesota", stateCode: "MN", slug: "minneapolis-mn", zipCodes: ["55401", "55402", "55403", "55404", "55405"], climate: "a humid continental climate with very cold, snowy winters and warm summers. Properly insulated and ventilated roofs are essential.", commonRisks: ["heavy snow loads", "ice dams", "freeze-thaw damage", "hailstorms"], localContent: { intro: "Minneapolis roofs are built for snow. Heavy loads are a given, and the structure must be able to handle the weight.", risks: "Like Chicago, ice dams are a major concern, and proper attic ventilation and insulation are the primary defense." } },
  { city: "Saint Paul", state: "Minnesota", stateCode: "MN", slug: "saint-paul-mn", zipCodes: ["55101", "55102", "55103", "55104", "55105"], climate: "faces extreme winter conditions, where ice dams and heavy snow can cause significant roofing problems.", commonRisks: ["ice dams", "heavy snowfall", "attic condensation", "summer hailstorms"], localContent: { intro: "Saint Paul shares the same frigid winter climate as its twin city, Minneapolis. Roofs must be winter-ready.", risks: "Inadequate ventilation can lead to condensation in the attic, which can rot the roof deck from the inside out." } },
  { city: "New York City", state: "New York", stateCode: "NY", slug: "new-york-city-ny", zipCodes: ["10001", "10002", "10003", "10004", "10005"], climate: "a humid continental climate with significant weather swings, from hot summers to cold winters with nor'easters.", commonRisks: ["heavy snow loads", "ice dams", "wind from coastal storms", "flat roof maintenance"], localContent: { intro: "Roofing in NYC is incredibly diverse, from historic brownstones to modern skyscrapers. Flat roofs are common and require specialized maintenance.", risks: "Coastal storms (nor'easters) can bring high winds and heavy precipitation (rain or snow), testing a roof's durability." } },
  { city: "Buffalo", state: "New York", stateCode: "NY", slug: "buffalo-ny", zipCodes: ["14201", "14202", "14203", "14204", "14206"], climate: "famous for its extreme lake-effect snow, requiring roofs built to handle immense snow loads.", commonRisks: ["extreme snow loads", "ice dams", "high winds", "freeze-thaw cycles"], localContent: { intro: "Buffalo is legendary for its lake-effect snow, which can dump multiple feet in a single storm. Roofs here are engineered for immense weight.", risks: "The sheer volume of snow makes Buffalo extremely prone to ice dams and structural damage from the snow load." } },
  { city: "Rochester", state: "New York", stateCode: "NY", slug: "rochester-ny", zipCodes: ["14604", "14605", "14606", "14607", "14608"], climate: "also experiences significant lake-effect snow and cold winters, making proper attic ventilation and insulation critical.", commonRisks: ["heavy snow", "ice dams", "poor ventilation issues", "wind"], localContent: { intro: "Rochester also gets hammered by lake-effect snow from Lake Ontario. A winter-proof roofing system is non-negotiable.", risks: "Properly functioning ventilation is critical to manage temperature and moisture in the attic during the long, cold winters." } },
  { city: "Charlotte", state: "North Carolina", stateCode: "NC", slug: "charlotte-nc", zipCodes: ["28202", "28203", "28204", "28205", "28206"], climate: "a humid subtropical climate with hot summers prone to thunderstorms and remnants of tropical systems.", commonRisks: ["hail", "high winds", "hurricanes remnants", "tree damage"], localContent: { intro: "Charlotte's weather is characterized by hot, humid summers that breed strong thunderstorms.", risks: "These storms can produce damaging hail and high winds. The area is also susceptible to the remnants of hurricanes, which bring sustained winds and heavy rain." } },
  { city: "Raleigh", state: "North Carolina", stateCode: "NC", slug: "raleigh-nc", zipCodes: ["27601", "27603", "27604", "27605", "27606"], climate: "similar to Charlotte, it gets a mix of severe thunderstorms in the summer and potential for winter ice storms.", commonRisks: ["hailstorms", "high winds", "pine needle accumulation", "ice storms"], localContent: { intro: "Raleigh's climate mirrors Charlotte's, with the addition of a significant pine tree population.", risks: "Clogged gutters from pine needles are a constant problem, and occasional winter ice storms can bring down limbs and power lines." } },
  { city: "Oklahoma City", state: "Oklahoma", stateCode: "OK", slug: "oklahoma-city-ok", zipCodes: ["73102", "73103", "73104", "73105", "73106"], climate: "located in the heart of 'Tornado Alley,' roofs must be built with extreme wind and hail resistance in mind.", commonRisks: ["tornadoes", "very large hail", "extreme high winds", "sudden temperature changes"], localContent: { intro: "Oklahoma City sits in the heart of Tornado Alley, arguably the most severe weather region in the country for roofing.", risks: "Baseball-sized hail, extreme winds, and tornadoes are a regular occurrence. Impact-resistant roofing is not just recommended; it's essential for survival." } },
  { city: "Tulsa", state: "Oklahoma", stateCode: "OK", slug: "tulsa-ok", zipCodes: ["74103", "74104", "74105", "74106", "74107"], climate: "also in Tornado Alley, it is one of the most at-risk cities in the US for severe hail and wind damage.", commonRisks: ["severe hailstorms", "tornadoes", "high winds", "heavy rainfall"], localContent: { intro: "Tulsa shares the extreme weather risks of Oklahoma City. Roofs are constantly under assault from the elements.", risks: "The frequency of severe hail and wind events means that homeowners often have multiple insurance claims over the life of a roof." } },
  { city: "Philadelphia", state: "Pennsylvania", stateCode: "PA", slug: "philadelphia-pa", zipCodes: ["19102", "19103", "19106", "19107", "19109"], climate: "a humid subtropical climate with four distinct seasons, including cold winters with snowfall and hot, humid summers.", commonRisks: ["snow loads", "ice dams", "wind from nor'easters", "aging rowhome roofs"], localContent: { intro: "Philadelphia's historic architecture, especially its many rowhomes with flat or low-slope roofs, requires specialized roofing knowledge.", risks: "These roofs are prone to ponding water, and the region's winter snow and ice can cause significant problems if not managed correctly." } },
  { city: "Pittsburgh", state: "Pennsylvania", stateCode: "PA", slug: "pittsburgh-pa", zipCodes: ["15212", "15219", "15222", "15224", "15226"], climate: "a humid continental climate with significant temperature swings and precipitation year-round.", commonRisks: ["freeze-thaw cycles", "heavy snow", "ice buildup", "aging housing stock"], localContent: { intro: "Pittsburgh's hilly terrain and older housing stock present unique roofing challenges. The weather is consistently variable.", risks: "The constant freeze-thaw cycles in winter are brutal on roofing materials, causing them to expand, contract, and crack over time." } },
  { city: "Nashville", state: "Tennessee", stateCode: "TN", slug: "nashville-tn", zipCodes: ["37201", "37203", "37204", "37205", "37206"], climate: "a humid subtropical climate with a high risk of severe thunderstorms, hail, and occasional tornadoes.", commonRisks: ["hail", "high winds", "tornadoes", "heavy rain"], localContent: { intro: "Nashville is prone to the same type of severe, pop-up thunderstorms as other parts of the Southeast.", risks: "These storms can develop quickly and often bring damaging hail and high winds that can strip shingles from a roof." } },
  { city: "Memphis", state: "Tennessee", stateCode: "TN", slug: "memphis-tn", zipCodes: ["38103", "38104", "38105", "38106", "38107"], climate: "experiences hot, humid summers and is at risk for severe weather, including high winds and hail from thunderstorms.", commonRisks: ["high winds", "hailstorms", "heavy rainfall", "high humidity"], localContent: { intro: "Memphis weather is hot and humid, creating a risk for severe thunderstorms throughout the summer.", risks: "Straight-line winds, known as 'derechos,' can cause widespread damage equivalent to a weak tornado." } },
  { city: "San Antonio", state: "Texas", stateCode: "TX", slug: "san-antonio-tx", zipCodes: ["78201", "78202", "78203", "78204", "78205"], climate: "a humid subtropical climate with very hot summers and a risk of severe hailstorms.", commonRisks: ["large hail", "high winds", "intense sun exposure", "flash flooding"], localContent: { intro: "San Antonio's climate is a punishing combination of intense heat and a significant risk of severe hailstorms.", risks: "The blistering sun degrades asphalt shingles, while spring storms can unleash large, destructive hail." } },
  { city: "Austin", state: "Texas", stateCode: "TX", slug: "austin-tx", zipCodes: ["78701", "78702", "78703", "78704", "78705"], climate: "a humid subtropical climate, characterized by hot summers and mild winters, with periods of heavy rain.", commonRisks: ["large hail", "flash floods", "strong thunderstorms", "wind damage"], localContent: { intro: "Austin is known for its 'flash flood' alley, where sudden, intense rainfall can overwhelm drainage systems, including gutters.", risks: "The area is also very prone to severe thunderstorms that produce large hail, making impact-resistant roofing a sound investment." } },
  { city: "Fort Worth", state: "Texas", stateCode: "TX", slug: "fort-worth-tx", zipCodes: ["76102", "76103", "76104", "76105", "76106"], climate: "often subject to severe weather, including some of the largest hail in the country.", commonRisks: ["very large hail", "tornadoes", "high winds", "extreme heat"], localContent: { intro: "Fort Worth sits squarely in the most severe hail zone in the US. Roofing here is all about impact resistance.", risks: "It is not uncommon for storms to produce hail the size of golf balls or larger, which can total a roof in minutes." } },
  { city: "Seattle", state: "Washington", stateCode: "WA", slug: "seattle-wa", zipCodes: ["98101", "98102", "98103", "98104", "98105"], climate: "an oceanic climate known for its persistent drizzle and rain, making moisture protection and moss prevention key.", commonRisks: ["persistent rain", "moss and algae growth", "windstorms", "poor ventilation"], localContent: { intro: "Seattle's reputation for rain is well-earned. Roofs must be designed as complete water-management systems.", risks: "The constant dampness is a perfect breeding ground for moss, which can lift shingles and trap moisture, leading to rot. Regular cleaning and zinc strips are common preventative measures." } },
  { city: "Tacoma", state: "Washington", stateCode: "WA", slug: "tacoma-wa", zipCodes: ["98402", "98403", "98404", "98405", "98406"], climate: "similar to Seattle, requiring roofing systems designed to manage constant moisture and prevent growth.", commonRisks: ["heavy rainfall", "moss growth", "wind damage", "gutter overflow"], localContent: { intro: "Tacoma shares Seattle's damp climate and the associated roofing challenges. Water management is the top priority.", risks: "Strong windstorms blowing in from the Puget Sound can also cause significant damage, especially to older roofs." } },
];

export const services = [
    {
        slug: "roof-repair",
        name: "Roof Repair",
        title: "Roof Repair",
        h1: "Roof Repair Services",
        description: "Get professional roof repair services in {city}, {state}. We connect you with top-rated local roofing contractors for leak repairs, shingle replacement, and more. Get a free, no-obligation inspection today."
    },
    {
        slug: "roof-replacement",
        name: "Roof Replacement",
        title: "Roof Replacement",
        h1: "Roof Replacement Services",
        description: "Need a new roof in {city}, {state}? We find trusted, local pros for complete roof replacements. High-quality materials and workmanship guaranteed. Contact us for a free estimate."
    },
    {
        slug: "emergency-roof-repair",
        name: "Emergency Roof Repair",
        title: "Emergency Roof Repair",
        h1: "Emergency Roof Repair",
        description: "24/7 emergency roof repair services in {city}, {state}. We quickly connect you with experts for urgent storm damage, leaks, and other roofing emergencies. Fast response to protect your home."
    },
    {
        slug: "storm-damage-roof",
        name: "Storm Damage Roof Repair",
        title: "Storm Damage Roof Repair",
        h1: "Storm Damage Roof Repair",
        description: "Specialized storm damage roof repair in {city}, {state}. Our network of roofers handles hail, wind, and hurricane damage. We assist with insurance claims. Schedule a free damage assessment now."
    },
    {
        slug: "roof-leak-repair",
        name: "Roof Leak Repair",
        title: "Roof Leak Repair",
        h1: "Roof Leak Repair",
        description: "Fast and reliable roof leak repair in {city}, {state}. Stop water damage now. We connect you with specialists who can find and fix any leak, big or small. Get your free quote."
    }
];

export const getNearbyCities = (currentState: string, currentCity: string): LocationData[] => {
  return locations
    .filter(loc => loc.state === currentState && loc.city !== currentCity)
    .slice(0, 4);
};

export const getServiceBySlug = (slug: string) => services.find(s => s.slug === slug);
export const getLocationBySlug = (slug: string) => locations.find(l => l.slug === slug);
