export interface LocationData {
  city: string;
  state: string;
  stateCode: string;
  slug: string;
  zipCodes: string[];
  climate: string;
  commonRisks: string[];
}

export const locations: LocationData[] = [
    // Arizona
  {
    city: "Phoenix",
    state: "Arizona",
    stateCode: "AZ",
    slug: "phoenix-az",
    zipCodes: ["85001", "85003", "85004", "85006", "85007"],
    climate: "a hot desert climate with very long, hot summers and short, mild winters, requiring materials that can withstand intense UV radiation.",
    commonRisks: ["intense sun exposure", "monsoon storms", "high winds"],
  },
  {
    city: "Mesa",
    state: "Arizona",
    stateCode: "AZ",
    slug: "mesa-az",
    zipCodes: ["85201", "85202", "85203", "85204", "85205"],
    climate: "a hot desert climate, similar to Phoenix, where reflective and heat-resistant roofing is critical.",
    commonRisks: ["intense sun exposure", "haboobs (dust storms)", "sudden downpours"],
  },
  {
    city: "Scottsdale",
    state: "Arizona",
    stateCode: "AZ",
    slug: "scottsdale-az",
    zipCodes: ["85250", "85251", "85253", "85254", "85255"],
    climate: "a hot arid climate where roofs must endure extreme summer heat and strong sunlight.",
    commonRisks: ["intense sun exposure", "monsoon storms", "tile roof maintenance"],
  },
  // California
  {
    city: "Los Angeles",
    state: "California",
    stateCode: "CA",
    slug: "los-angeles-ca",
    zipCodes: ["90001", "90002", "90003", "90004", "90005"],
    climate: "a Mediterranean climate with hot, dry summers and mild, wet winters. Title 24 compliance for cool roofs is a key factor.",
    commonRisks: ["intense sun exposure", "wildfire embers", "earthquakes (requires secure fastening)"],
  },
  {
    city: "San Diego",
    state: "California",
    stateCode: "CA",
    slug: "san-diego-ca",
    zipCodes: ["92101", "92102", "92103", "92104", "92105"],
    climate: "a mild Mediterranean climate year-round, but coastal salt air can accelerate corrosion on certain roofing materials.",
    commonRisks: ["salt air corrosion", "intense sun exposure", "wildfire risk in inland areas"],
  },
  {
    city: "San Jose",
    state: "California",
    stateCode: "CA",
    slug: "san-jose-ca",
    zipCodes: ["95101", "95110", "95111", "95112", "95113"],
    climate: "a mild Mediterranean climate with warm, dry summers and cool, wet winters.",
    commonRisks: ["intense sun exposure", "heat absorption", "winter rain leaks"],
  },
  {
    city: "Sacramento",
    state: "California",
    stateCode: "CA",
    slug: "sacramento-ca",
    zipCodes: ["95811", "95814", "95815", "95816", "95817"],
    climate: "a hot-summer Mediterranean climate, with very hot, dry summers requiring energy-efficient roofing.",
    commonRisks: ["extreme summer heat", "heavy rain in winter", "tree debris"],
  },
  {
    city: "Fresno",
    state: "California",
    stateCode: "CA",
    slug: "fresno-ca",
    zipCodes: ["93650", "93701", "93702", "93703", "93704"],
    climate: "a semi-arid climate with very hot, dry summers and cool, damp winters, with dense Tule fog.",
    commonRisks: ["extreme heat", "UV degradation", "poor air quality affecting materials"],
  },
  // Colorado
  {
    city: "Denver",
    state: "Colorado",
    stateCode: "CO",
    slug: "denver-co",
    zipCodes: ["80202", "80203", "80204", "80205", "80206"],
    climate: "a semi-arid climate with four distinct seasons. High altitude means intense UV exposure and a high risk of severe hailstorms.",
    commonRisks: ["severe hailstorms", "high winds", "heavy snowfall", "intense sun exposure"],
  },
  {
    city: "Aurora",
    state: "Colorado",
    stateCode: "CO",
    slug: "aurora-co",
    zipCodes: ["80010", "80011", "80012", "80013", "80014"],
    climate: "similar to Denver, it experiences frequent and severe hail, making impact-resistant shingles (Class 4) a popular choice.",
    commonRisks: ["large hail", "strong winds", "freeze-thaw cycles", "heavy snow loads"],
  },
  {
    city: "Colorado Springs",
    state: "Colorado",
    stateCode: "CO",
    slug: "colorado-springs-co",
    zipCodes: ["80903", "80904", "80905", "80906", "80907"],
    climate: "located at the foot of the Rockies, it is highly prone to severe hailstorms, high winds, and rapid temperature changes.",
    commonRisks: ["severe hailstorms", "high winds", "wildfire risk", "heavy snow"],
  },
  // Florida
  {
    city: "Miami",
    state: "Florida",
    stateCode: "FL",
    slug: "miami-fl",
    zipCodes: ["33101", "33109", "33125", "33126", "33127"],
    climate: "a tropical monsoon climate, prone to hurricanes and tropical storms, demanding robust, high-wind-rated roofing solutions.",
    commonRisks: ["hurricanes", "high winds", "heavy rainfall", "intense sun exposure"],
  },
  {
    city: "Fort Lauderdale",
    state: "Florida",
    stateCode: "FL",
    slug: "fort-lauderdale-fl",
    zipCodes: ["33301", "33304", "33305", "33306", "33308"],
    climate: "a tropical rainforest climate, with significant hurricane risk and high humidity.",
    commonRisks: ["hurricanes", "wind-driven rain", "salt air corrosion", "high humidity"],
  },
  {
    city: "West Palm Beach",
    state: "Florida",
    stateCode: "FL",
    slug: "west-palm-beach-fl",
    zipCodes: ["33401", "33403", "33404", "33405", "33406"],
    climate: "a tropical climate with a high risk of hurricanes and severe thunderstorms.",
    commonRisks: ["hurricanes", "high winds", "torrential rain", "intense sun exposure"],
  },
  {
    city: "Orlando",
    state: "Florida",
    stateCode: "FL",
    slug: "orlando-fl",
    zipCodes: ["32801", "32803", "32804", "32805", "32806"],
    climate: "a humid subtropical climate with a strong wet season, leading to frequent thunderstorms and hurricane risk.",
    commonRisks: ["hurricanes", "hailstorms", "high humidity causing algae growth", "heavy rainfall"],
  },
  {
    city: "Tampa",
    state: "Florida",
    stateCode: "FL",
    slug: "tampa-fl",
    zipCodes: ["33602", "33603", "33604", "33605", "33606"],
    climate: "a humid subtropical climate on the Gulf Coast, making it vulnerable to hurricanes and tropical storms.",
    commonRisks: ["hurricanes", "high winds", "storm surge", "high humidity"],
  },
  {
    city: "Jacksonville",
    state: "Florida",
    stateCode: "FL",
    slug: "jacksonville-fl",
    zipCodes: ["32202", "32204", "32205", "32206", "32207"],
    climate: "a humid subtropical climate with milder winters than South Florida but still at risk from hurricanes and nor'easters.",
    commonRisks: ["hurricanes", "high winds", "heavy rainfall", "hail"],
  },
  // Georgia
  {
    city: "Atlanta",
    state: "Georgia",
    stateCode: "GA",
    slug: "atlanta-ga",
    zipCodes: ["30303", "30305", "30306", "30307", "30308"],
    climate: "a humid subtropical climate known for hot, humid summers and occasional winter ice storms.",
    commonRisks: ["high winds from thunderstorms", "hail", "tree limbs falling", "ice storms"],
  },
  {
    city: "Marietta",
    state: "Georgia",
    stateCode: "GA",
    slug: "marietta-ga",
    zipCodes: ["30006", "30008", "30060", "30062", "30064"],
    climate: "similar to Atlanta, with a high risk of damage from severe thunderstorms and falling pine trees.",
    commonRisks: ["hail", "wind damage", "pine needle buildup in gutters", "high humidity"],
  },
  // Illinois
  {
    city: "Chicago",
    state: "Illinois",
    stateCode: "IL",
    slug: "chicago-il",
    zipCodes: ["60601", "60602", "60603", "60604", "60605"],
    climate: "a humid continental climate with hot summers, cold, snowy winters, and strong winds off Lake Michigan.",
    commonRisks: ["heavy snow loads", "ice dams", "high winds", "freeze-thaw cycles"],
  },
  {
    city: "Naperville",
    state: "Illinois",
    stateCode: "IL",
    slug: "naperville-il",
    zipCodes: ["60540", "60563", "60564", "60565"],
    climate: "experiences the full range of Midwestern weather, from hot summers to brutally cold winters with significant snowfall.",
    commonRisks: ["ice dams", "heavy snow", "hailstorms", "high winds"],
  },
  // Louisiana
  {
    city: "New Orleans",
    state: "Louisiana",
    stateCode: "LA",
    slug: "new-orleans-la",
    zipCodes: ["70112", "70113", "70114", "70115", "70116"],
    climate: "a humid subtropical climate with a very high risk of hurricanes, tropical storms, and heavy rainfall.",
    commonRisks: ["hurricanes", "torrential rain and flooding", "high humidity and mold growth", "storm surge"],
  },
  {
    city: "Baton Rouge",
    state: "Louisiana",
    stateCode: "LA",
    slug: "baton-rouge-la",
    zipCodes: ["70801", "70802", "70803", "70805", "70806"],
    climate: "inland from the coast but still very susceptible to hurricane remnants, high winds, and heavy rainfall.",
    commonRisks: ["hurricanes", "high winds", "hailstorms", "heavy rainfall"],
  },
  // Minnesota
  {
    city: "Minneapolis",
    state: "Minnesota",
    stateCode: "MN",
    slug: "minneapolis-mn",
    zipCodes: ["55401", "55402", "55403", "55404", "55405"],
    climate: "a humid continental climate with very cold, snowy winters and warm summers. Properly insulated and ventilated roofs are essential.",
    commonRisks: ["heavy snow loads", "ice dams", "freeze-thaw damage", "hailstorms"],
  },
  {
    city: "Saint Paul",
    state: "Minnesota",
    stateCode: "MN",
    slug: "saint-paul-mn",
    zipCodes: ["55101", "55102", "55103", "55104", "55105"],
    climate: "faces extreme winter conditions, where ice dams and heavy snow can cause significant roofing problems.",
    commonRisks: ["ice dams", "heavy snowfall", "attic condensation", "summer hailstorms"],
  },
  // New York
  {
    city: "New York City",
    state: "New York",
    stateCode: "NY",
    slug: "new-york-city-ny",
    zipCodes: ["10001", "10002", "10003", "10004", "10005"],
    climate: "a humid continental climate with significant weather swings, from hot summers to cold winters with nor'easters.",
    commonRisks: ["heavy snow loads", "ice dams", "wind damage from coastal storms", "flat roof maintenance"],
  },
  {
    city: "Buffalo",
    state: "New York",
    stateCode: "NY",
    slug: "buffalo-ny",
    zipCodes: ["14201", "14202", "14203", "14204", "14206"],
    climate: "famous for its extreme lake-effect snow, requiring roofs built to handle immense snow loads.",
    commonRisks: ["extreme snow loads", "ice dams", "high winds", "freeze-thaw cycles"],
  },
  {
    city: "Rochester",
    state: "New York",
    stateCode: "NY",
    slug: "rochester-ny",
    zipCodes: ["14604", "14605", "14606", "14607", "14608"],
    climate: "also experiences significant lake-effect snow and cold winters, making proper attic ventilation and insulation critical.",
    commonRisks: ["heavy snow", "ice dams", "poor ventilation issues", "wind"],
  },
  // North Carolina
  {
    city: "Charlotte",
    state: "North Carolina",
    stateCode: "NC",
    slug: "charlotte-nc",
    zipCodes: ["28202", "28203", "28204", "28205", "28206"],
    climate: "a humid subtropical climate with hot summers prone to thunderstorms and remnants of tropical systems.",
    commonRisks: ["hail", "high winds", "hurricanes remnants", "tree damage"],
  },
  {
    city: "Raleigh",
    state: "North Carolina",
    stateCode: "NC",
    slug: "raleigh-nc",
    zipCodes: ["27601", "27603", "27604", "27605", "27606"],
    climate: "similar to Charlotte, it gets a mix of severe thunderstorms in the summer and potential for winter ice storms.",
    commonRisks: ["hailstorms", "high winds", "pine needle accumulation", "ice storms"],
  },
  // Oklahoma
  {
    city: "Oklahoma City",
    state: "Oklahoma",
    stateCode: "OK",
    slug: "oklahoma-city-ok",
    zipCodes: ["73102", "73103", "73104", "73105", "73106"],
    climate: "located in the heart of 'Tornado Alley,' roofs must be built with extreme wind and hail resistance in mind.",
    commonRisks: ["tornadoes", "very large hail", "extreme high winds", "sudden temperature changes"],
  },
  {
    city: "Tulsa",
    state: "Oklahoma",
    stateCode: "OK",
    slug: "tulsa-ok",
    zipCodes: ["74103", "74104", "74105", "74106", "74107"],
    climate: "also in Tornado Alley, it is one of the most at-risk cities in the US for severe hail and wind damage.",
    commonRisks: ["severe hailstorms", "tornadoes", "high winds", "heavy rainfall"],
  },
  // Pennsylvania
  {
    city: "Philadelphia",
    state: "Pennsylvania",
    stateCode: "PA",
    slug: "philadelphia-pa",
    zipCodes: ["19102", "19103", "19106", "19107", "19109"],
    climate: "a humid subtropical climate with four distinct seasons, including cold winters with snowfall and hot, humid summers.",
    commonRisks: ["snow loads", "ice dams", "wind from nor'easters", "aging rowhome roofs"],
  },
  {
    city: "Pittsburgh",
    state: "Pennsylvania",
    stateCode: "PA",
    slug: "pittsburgh-pa",
    zipCodes: ["15212", "15219", "15222", "15224", "15226"],
    climate: "a humid continental climate with significant temperature swings and precipitation year-round.",
    commonRisks: ["freeze-thaw cycles", "heavy snow", "ice buildup", "aging housing stock"],
  },
  // Tennessee
  {
    city: "Nashville",
    state: "Tennessee",
    stateCode: "TN",
    slug: "nashville-tn",
    zipCodes: ["37201", "37203", "37204", "37205", "37206"],
    climate: "a humid subtropical climate with a high risk of severe thunderstorms, hail, and occasional tornadoes.",
    commonRisks: ["hail", "high winds", "tornadoes", "heavy rain"],
  },
  {
    city: "Memphis",
    state: "Tennessee",
    stateCode: "TN",
    slug: "memphis-tn",
    zipCodes: ["38103", "38104", "38105", "38106", "38107"],
    climate: "experiences hot, humid summers and is at risk for severe weather, including high winds and hail from thunderstorms.",
    commonRisks: ["high winds", "hailstorms", "heavy rainfall", "high humidity"],
  },
  // Texas
  {
    city: "Houston",
    state: "Texas",
    stateCode: "TX",
    slug: "houston-tx",
    zipCodes: ["77002", "77003", "77004", "77005", "77006"],
    climate: "a humid subtropical climate, with hot, humid summers and mild winters, making durable roofing materials essential.",
    commonRisks: ["hurricanes", "hailstorms", "heavy rainfall", "high winds"],
  },
  {
    city: "Dallas",
    state: "Texas",
    stateCode: "TX",
    slug: "dallas-tx",
    zipCodes: ["75201", "75202", "75203", "75204", "75205"],
    climate: "a humid subtropical climate with very hot summers, requiring roofs that can handle extreme heat and intense sun.",
    commonRisks: ["severe hailstorms", "tornadoes", "strong winds", "intense sun exposure"],
  },
  {
    city: "San Antonio",
    state: "Texas",
    stateCode: "TX",
    slug: "san-antonio-tx",
    zipCodes: ["78201", "78202", "78203", "78204", "78205"],
    climate: "a humid subtropical climate with very hot summers and a risk of severe hailstorms.",
    commonRisks: ["large hail", "high winds", "intense sun exposure", "flash flooding"],
  },
  {
    city: "Austin",
    state: "Texas",
    stateCode: "TX",
    slug: "austin-tx",
    zipCodes: ["78701", "78702", "78703", "78704", "78705"],
    climate: "a humid subtropical climate, characterized by hot summers and mild winters, with periods of heavy rain.",
    commonRisks: ["large hail", "flash floods", "strong thunderstorms", "wind damage"],
  },
  {
    city: "Fort Worth",
    state: "Texas",
    stateCode: "TX",
    slug: "fort-worth-tx",
    zipCodes: ["76102", "76103", "76104", "76105", "76106"],
    climate: "often subject to severe weather, including some of the largest hail in the country.",
    commonRisks: ["very large hail", "tornadoes", "high winds", "extreme heat"],
  },
  // Washington
  {
    city: "Seattle",
    state: "Washington",
    stateCode: "WA",
    slug: "seattle-wa",
    zipCodes: ["98101", "98102", "98103", "98104", "98105"],
    climate: "an oceanic climate known for its persistent drizzle and rain, making moisture protection and moss prevention key.",
    commonRisks: ["persistent rain", "moss and algae growth", "windstorms", "poor ventilation"],
  },
  {
    city: "Tacoma",
    state: "Washington",
    stateCode: "WA",
    slug: "tacoma-wa",
    zipCodes: ["98402", "98403", "98404", "98405", "98406"],
    climate: "similar to Seattle, requiring roofing systems designed to manage constant moisture and prevent growth.",
    commonRisks: ["heavy rainfall", "moss growth", "wind damage", "gutter overflow"],
  },
];

export const services = [
    {
        slug: "roof-repair",
        name: "Roof Repair",
        title: "Roof Repair",
        h1: "Roof Repair Services in",
        description: "Get professional roof repair services in {city}, {state}. We connect you with top-rated local roofing contractors for leak repairs, shingle replacement, and more. Get a free, no-obligation inspection today."
    },
    {
        slug: "roof-replacement",
        name: "Roof Replacement",
        title: "Roof Replacement",
        h1: "Roof Replacement Services in",
        description: "Need a new roof in {city}, {state}? We find trusted, local pros for complete roof replacements. High-quality materials and workmanship guaranteed. Contact us for a free estimate."
    },
    {
        slug: "emergency-roof-repair",
        name: "Emergency Roof Repair",
        title: "Emergency Roof Repair",
        h1: "Emergency Roof Repair in",
        description: "24/7 emergency roof repair services in {city}, {state}. We quickly connect you with experts for urgent storm damage, leaks, and other roofing emergencies. Fast response to protect your home."
    },
    {
        slug: "storm-damage-roof",
        name: "Storm Damage Roof Repair",
        title: "Storm Damage Roof Repair",
        h1: "Storm Damage Roof Repair in",
        description: "Specialized storm damage roof repair in {city}, {state}. Our network of roofers handles hail, wind, and hurricane damage. We assist with insurance claims. Schedule a free damage assessment now."
    },
    {
        slug: "roof-leak-repair",
        name: "Roof Leak Repair",
        title: "Roof Leak Repair",
        h1: "Roof Leak Repair in",
        description: "Fast and reliable roof leak repair in {city}, {state}. Stop water damage now. We connect you with specialists who can find and fix any leak, big or small. Get your free quote."
    }
];

export const getServiceBySlug = (slug: string) => services.find(s => s.slug === slug);
export const getLocationBySlug = (slug: string) => locations.find(l => l.slug === slug);
